name: CI

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -lock=false -var-file="terraform.tfvars"
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
          TF_VAR_acr_admin_username: ${{ secrets.ACR_ADMIN_USERNAME }}  # Inject sensitive value here
          TF_VAR_acr_admin_password: ${{ secrets.ACR_ADMIN_PASSWORD }}  # Inject sensitive value here

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve -lock=false -var-file="terraform.tfvars"
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
          TF_VAR_acr_admin_username: ${{ secrets.ACR_ADMIN_USERNAME }}  # Inject sensitive value here
          TF_VAR_acr_admin_password: ${{ secrets.ACR_ADMIN_PASSWORD }}  # Inject sensitive value here
