name: CI

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Decode terraform.tfvars
        run: echo "${{ secrets.TFVARS_BASE64 }}" | base64 --decode > terraform.tfvars

      - name: Enable Terraform Debug Logging
        run: echo "TF_LOG=DEBUG" >> $GITHUB_ENV

      - name: Terraform Init
        run: terraform init
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -lock=false -var-file="terraform.tfvars"
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
          ACR_ADMIN_USERNAME: ${{ secrets.ACR_ADMIN_USERNAME }}
          ACR_ADMIN_PASSWORD: ${{ secrets.ACR_ADMIN_PASSWORD }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
          ACR_RESOURCE_GROUP_NAME: ${{ secrets.ACR_RESOURCE_GROUP_NAME }}

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve -lock=false -var-file="terraform.tfvars"
        env:
          ARM_SAS_TOKEN: ${{ secrets.ARM_SAS_TOKEN }}
          ACR_ADMIN_USERNAME: ${{ secrets.ACR_ADMIN_USERNAME }}
          ACR_ADMIN_PASSWORD: ${{ secrets.ACR_ADMIN_PASSWORD }}
          ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
          ACR_NAME: ${{ secrets.ACR_NAME }}
          ACR_RESOURCE_GROUP_NAME: ${{ secrets.ACR_RESOURCE_GROUP_NAME }}
