name: CI

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Create terraform.tfvars
        run: |
          echo "resource_group_name = \"tfResourceGroup\"" > terraform.tfvars
          echo "location = \"East US\"" >> terraform.tfvars
          echo "acr_name = \"c2cacr\"" >> terraform.tfvars
          echo "acr_resource_group_name = \"c2c-demo\"" >> terraform.tfvars
          echo "acr_login_server = \"${{ secrets.ACR_LOGIN_SERVER }}\"" >> terraform.tfvars
          echo "acr_admin_username = \"${{ secrets.ACR_ADMIN_USERNAME }}\"" >> terraform.tfvars
          echo "acr_admin_password = \"${{ secrets.ACR_ADMIN_PASSWORD }}\"" >> terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve -var-file="terraform.tfvars"

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve -var-file="terraform.tfvars"
